name: drupal
recipe: drupal10
config:
  webroot: web
  via: apache:2.4.38
  php: '8.1'
  database: mariadb:10.4

services:
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
