name: project-template

#recipe: drupal10

services:
#  appserver:
  php:
    via: apache:2.4.38
#    via: nginx:1.23
    type: php:8.1
    webroot: public
    ssl: true
    sslExpose: false
#    composer_version: 2
#    xdebug: true
#    build:
#      - composer install
#    run:
#      - drush sql:drop -y
#      - drush sql:cli < db-startup.sql
#      - drush updatedb -y
#      - drush config:import -y
#      - drush php:eval 'node_access_rebuild();'
#      - drush locale:import cs /app/private/translations/cs.po
#      - drush cache:rebuild
#      - drush core:cron
#      - chmod 444 public/sites/default/settings.php
#      - chmod 444 public/sites/default/settings.local.php
  mariadb:
    type: mariadb:10.4
    creds:
      user: mariadb
      password: mariadb
      database: mariadb
  postgres:
    type: postgres:10
    creds:
      user: postgres
      password: postgres
      database: postgres
  node:
    type: node:18
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - mariadb
    ssl: true
    sslExpose: false
  adminer:
    type: compose
    services:
      image: adminer:4-standalone
      command: php -S [::]:8080 -t /var/www/html
    ports:
      - '8080'
    moreHttpPorts:
      - '8080'
    ssl: true
    sslExpose: false
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
#      - appserver
      - php
    ssl: true
    sslExpose: false
proxy:
  php:
    - project-template.lndo.site
  phpmyadmin:
    - phpmyadmin-project-template.lndo.site
  adminer:
    - adminer-project-template.lndo.site:8080
  mailhog:
    - mailhog-project-template.lndo.site

tooling:
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
  xdebug-on:
#    service: appserver
    service: php
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
#    service: appserver
    service: php
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
#  xdebug-on:
##    service: appserver
#    service: php
#    description: Enable xdebug for nginx.
#    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
#    user: root
#  xdebug-off:
##    service: appserver
#    service: php
#    description: Disable xdebug for nginx.
#    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
#    user: root
#  drush:
##    service: appserver
#    service: php
#    env:
#      DRUSH_OPTIONS_URI: 'https://project-template.lndo.site'
  clone-webserver-info:
    service: php
    description: Clone webserver-info project into public directory (backup current public directory).
    cmd: "mv /app/public /app/public_backup && git clone https://gitlab.com/vavyskov/webserver-info.git /tmp/webserver-info && cp -r /tmp/webserver-info/src/. /app/public && rm -fr /tmp/webserver-info"
