name: wordpress
recipe: wordpress
config:
  webroot: public
  via: apache:2.4.62
  php: '8.2'
  database: mariadb:11.5

services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y zip mc
      - mkdir -p /home/www-data/.config/mc
      - printf "[Midnight-Commander]\nuse_internal_edit=1\n" > /home/www-data/.config/mc/ini
      - chown -R www-data:www-data /home/www-data/.config
  adminer:
    type: compose
    services:
      image: adminer:4-standalone
      command: php -S [::]:8080 -t /var/www/html
    ports:
      - '8080'
    moreHttpPorts:
      - '8080'
    ssl: true
    sslExpose: false
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
    ssl: true
    sslExpose: false
proxy:
  adminer:
    - adminer-wordpress.lndo.site:8080
  mailhog:
    - mailhog-wordpress.lndo.site